name: Node.js Server CI

on:
  push:
    branches: main
    paths:
      - 'server/**'
      - '.github/workflows/**'
  pull_request:
    branches: main
    paths:
      - 'server/**'
      - '.github/workflows/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v7
    - name: Use Node.js
      uses: actions/setup-node@v7
      with:
        node-version: '20.x'
        cache: 'npm'
        cache-dependency-path: server/package-lock.json
    - run: cd server && npm install --prefer-offline --fetch-retries 3 --fetch-retry-mintimeout 5000

    - name: Set Environment Variables
      run: |
        echo "AZURE_STORAGE_ACCOUNT_NAME=${{ secrets.AZURE_STORAGE_ACCOUNT_NAME }}" >> $GITHUB_ENV
        echo "AZURE_STORAGE_ACCESS_KEY=${{ secrets.AZURE_STORAGE_ACCESS_KEY }}" >> $GITHUB_ENV

    - run: cd server && npm test
      env:
        CI: true
